"""Add archived to issue table

Revision ID: 30096e50dba8
Revises: b07e3c6a0c71
Create Date: 2023-07-04 14:49:52.265609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30096e50dba8'
down_revision = 'b07e3c6a0c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
