"""Change projects.token to be unique

Revision ID: 899fc039e941
Revises: 2be1367e8d7b
Create Date: 2023-01-21 18:18:28.047360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899fc039e941'
down_revision = '2be1367e8d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
